# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.bow.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'bow', 'function_path': 'animated_java:bow/animations/airstrike/next_frame'}
execute if score @s aj.airstrike.frame matches 81.. run scoreboard players set @s aj.airstrike.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.airstrike.frame
execute at @s run function animated_java:bow/animations/airstrike/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.airstrike.frame 1