# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.bow.root] run return 0
execute on passengers if entity @s[tag=aj.bow.data] unless data entity @s {data:{rigHash: '2f961c96318a9fd92829c35ed8a3110d27aa954823dbe4000d449a1141cdbddf'}} on vehicle run function animated_java:bow/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1