# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute at @s run tp @s ~ ~ ~ facing entity @r[distance=..8]
execute at @s run tp @s ~ ~ ~ ~ 0