# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display15] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display15 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display16] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display16 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display12] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display12 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display18] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display18 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display11] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display9] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display21] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display21 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display19] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display19 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display17] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display17 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display14] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display14 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display8] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display13] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display13 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display10] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.curse_of_midas.node.item_display] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display set from storage aj:uuid main.out