# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.haunted_sword.root] run return 0
execute on passengers if entity @s[tag=aj.haunted_sword.data] unless data entity @s {data:{rigHash: 'a7094099c297f6e51bfe383d027a8911939805b8e39330f4d085b37b0fd34e7b'}} on vehicle run function animated_java:haunted_sword/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1