# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.haunted_sword.root] run return 0
execute on passengers if entity @s[tag=aj.haunted_sword.data] unless data entity @s {data:{rigHash: '2ee29acb29d1b273e95d52a9178979fd26fb3d8cb762b825cf87a6c2454baf86'}} on vehicle run function animated_java:haunted_sword/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1