# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.haunted_sword.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.haunted_sword.animation.idle.playing] run function animated_java:haunted_sword/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.haunted_sword.animation.slash.playing] run function animated_java:haunted_sword/animations/slash/zzz/on_tick
execute if entity @s[tag=aj.haunted_sword.animation.cut.playing] run function animated_java:haunted_sword/animations/cut/zzz/on_tick
execute if entity @s[tag=aj.haunted_sword.animation.shockwave.playing] run function animated_java:haunted_sword/animations/shockwave/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~