# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.haunted_sword.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'haunted_sword', 'function_path': 'animated_java:haunted_sword/animations/shockwave/next_frame'}
execute if score @s aj.shockwave.frame matches 78.. run scoreboard players set @s aj.shockwave.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.shockwave.frame
execute at @s run function animated_java:haunted_sword/animations/shockwave/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.shockwave.frame 1