# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.curse_of_midas.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'curse_of_midas', 'function_path': 'animated_java:curse_of_midas/animations/area_attack/next_frame'}
execute if score @s aj.area_attack.frame matches 91.. run scoreboard players set @s aj.area_attack.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.area_attack.frame
execute at @s run function animated_java:curse_of_midas/animations/area_attack/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.area_attack.frame 1