# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.slash.frame dummy
scoreboard objectives add aj.cut.frame dummy
scoreboard objectives add aj.shockwave.frame dummy