# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.bow.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'bow', 'function_path': 'animated_java:bow/animations/shoot/resume'}
tag @s add aj.bow.animation.shoot.playing