# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.curse_of_midas.root] run return 0
execute on passengers if entity @s[tag=aj.curse_of_midas.data] unless data entity @s {data:{rigHash: '11a60f80f19896ab48333b4b8be8667aaccf7d8466e9a834bce65013f7d51f97'}} on vehicle run function animated_java:curse_of_midas/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1