# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.curse_of_midas.root] run return 0
execute on passengers if entity @s[tag=aj.curse_of_midas.data] unless data entity @s {data:{rigHash: '37593bc4db7e08568e199087b0f50601e14ed5d015466226372440e4497cbed5'}} on vehicle run function animated_java:curse_of_midas/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1